version: '2'

services:
  eureka:
    image: eureka-micro:1.0
    hostname: eureka
    ports:
     - "8761:8761"
    networks:
     - basic

  config:
    image: config-micro:1.0
    hostname: config
    networks:
     - basic
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
    ports:
      - "7070:7070"

  pong:
    image: pong-micro:1.0
    hostname: pong
    networks:
     - basic
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
       SERVER_PORT: 8080
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    depends_on:
      - eureka
      - config

  ping:
    image: ping-micro:1.0
    hostname: ping
    networks:
     - basic
    environment:
       EUREKA_HOST: eureka
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - config

networks:
  basic: